on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch: {}

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        debian_codename: [ "bullseye", "bookworm" ]
        php_version: [ "8.1", "8.2", "8.3" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,event=push,enable={{ is_default_branch }},value=${{ matrix.php_version }}
            type=raw,event=push,enable={{ is_default_branch }},value=${{ matrix.php_version }}-${{ matrix.debian_codename }}
            type=sha,event=push,enable={{ is_default_branch }},prefix=${{ matrix.php_version }}-${{ matrix.debian_codename }}-,format=short
            type=sha,event=push,enable=true,prefix=branch-{{ branch }}-${{ matrix.php_version }}-${{ matrix.debian_codename }}-,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DEBIAN_CODENAME=${{ matrix.debian_codename }}
            PHP_VERSION=${{ matrix.php_version }}
